title: Stanford FLAME AI Workshop 2023
description: "FLAME: Future Learning Approaches for Modeling and Engineering"
venue: "Dates: Sept 5 to Sept 15 2023 | Venue: Virtual"
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman

github:
  about_url: ./index.html
  apply_url: https://www.eventbrite.com/e/stanford-flame-ai-workshop-2023-tickets-593756701277
  contact_url: "mailto:flame.ai.workshop@gmail.com"
  organizer_url: ./organizers.html
  flyer_url: ./assets/img/flyer.pdf
  # 2023_url: ../index.html
