title: Stanford FLAME AI Workshop
description: Future Learning Approaches for Modeling and Engineering Combustion
venue: "Dates: Summer 2023 | Venue: Virtual/Hybrid at Stanford University"
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman

github:
  about_url: ./index.html
  apply_url: https://www.eventbrite.com/e/stanford-flame-ai-workshop-2023-tickets-593756701277
  contact_url: "mailto:flame.ai.workshop@gmail.com"
